#!/bin/sh

set -o errexit -o nounset

umask 077

mkdir -p /etc/nginx/session_ticket_keys
mount -t ramfs -o mode=700 ramfs /etc/nginx/session_ticket_keys

for i in 1 2 3 4; do
	dd ibs=1 obs=1 count='80' 2>/dev/null </dev/urandom >"/etc/nginx/session_ticket_keys/$i.key"
done
